### ISSUE TITLE
cannot play video on NOKIA XR20 {"error": {"extra": 0, "what": -38}}

### ISSUE THREAD

**Issue by SamuelWongRedSo** [TheWidlarzGroup/react-native-video#3201]
# Bug
cannot play video on **NOKIA XR20**(works well on other devices) and get error {"error": {"extra": 0, "what": -38}}. Since there is no doc on the above error, can anyone help me?

## Platform
Which player are you experiencing the problem on:
* Android
## Environment info

Library version: 5.2.1
Device: NOKIA XR20
Android version: 13

```
<Video
    source={require('local_video.mp4')}
    muted
    style={{
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
    }}
    resizeMode="cover"
    onEnd={onEnd}
    onError={error => {
      Alert.alert('video error', JSON.stringify(error), [
        {
          text: 'skip',
          onPress: onEnd,
          style: 'cancel',
        },
      ]);
    }}
  />
```
![image](https://github.com/react-native-video/react-native-video/assets/99625536/20ac5556-de8c-476b-890b-bb770529df60)

**Comment by freeboub** [comment]
can you please detail error in logcat please ? I suspect a codec issue

**Comment by SamuelWongRedSo** [comment]
sorry, I do not own the device now, so I cannot get the detail in logcat, but I get the error below.
![image](https://github.com/react-native-video/react-native-video/assets/99625536/4c6a96c9-20b3-47fb-a186-f26660bf38a2)
according to [https://developer.android.com/guide/topics/media/platform/supported-formats#video-formats](https://developer.android.com/guide/topics/media/platform/supported-formats#video-formats),
H.264 AVC Main Profile should be supported

**Comment by freeboub** [comment]
Do you keep too much video view in the dom ?
This issue happens when too many videos are played at the same time..

**Comment by SamuelWongRedSo** [comment]
it is the only Video component in my app, I play the video when the app start, 
below is a simplification of the code
```
isReady ? <Main /> : <Video
        source={source}
        muted
        style={styles.container}
        resizeMode="cover"
        onEnd={() => setReady(true)}
        onError={error => {
          Alert.alert('video error', JSON.stringify(error), [
            {
              text: 'skip',
              onPress: () => setReady(true),
              style: 'cancel',
            },
          ]);
        }}
      />
```

**Comment by angelos3lex** [comment]
I get similar issues from a user on Xiaomi Pad 5.

`{"error":{"extra":-2147479543,"what":1}}`
`{"error":{"extra":-38,"what":1}}`
`{"error":{"extra":0,"what":-38}}`

The videos he is trying to load are all captured using react-native-vision-camera, so they are already recorded well through his camera app and he can successfully watch them if he manually finds them through the documents. But, when he tries to see them through our app, using this lib, we get above errors.

It's very strange, the numbers we get in the errors are not documented in the MediaPlayer docs:
https://developer.android.com/reference/android/media/MediaPlayer#constants_1

Any idea where to find what `-38` or `-2147479543` mean?

**Comment by freeboub** [comment]
Did you try to switch on react native video v6.0.0 ?

**Comment by angelos3lex** [comment]
Good idea, will try.
After update (v6.0.0-beta.0) , when trying to display the captured video on my test, i get the following crash, any idea?
```
FATAL EXCEPTION: main
     Process: com.mypackage.name, PID: 13405
     java.lang.NoSuchMethodError: No static method registerReceiver(Landroid/content/Context;Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in /data/app/com.mypackage.nam-eFoTqysjT8guavhQQzwmjuQ==/base.apk)    
     at com.brentvatne.receiver.AudioBecomingNoisyReceiver.setListener(AudioBecomingNoisyReceiver.java:30)
     at com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerCore(ReactExoplayerView.java:635)
     at com.brentvatne.exoplayer.ReactExoplayerView.lambda$initializePlayer$6$com-brentvatne-exoplayer-ReactExoplayerView(ReactExoplayerView.java:547)
     at com.brentvatne.exoplayer.ReactExoplayerView$$ExternalSyntheticLambda11.run(Unknown Source:6)
     at android.os.Handler.handleCallback(Handler.java:883)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:237)
     at android.app.ActivityThread.main(ActivityThread.java:8107)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
     
Opened this in new issue: https://github.com/react-native-video/react-native-video/issues/3379

**Comment by angelos3lex** [comment]
@freeboub User verified it works with 6.0.0-beta.0 :D

**Comment by freeboub** [comment]
So let's close, thanks
