### ISSUE TITLE
[BUG]: seek() throws TypeError: _VideoNativeComponent.VideoManager.seek is not a function (it is undefined)

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3637]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

This is with beta 6 on Android  - I would try beta7 but it doesn't build for me.

My code snippet looks like this:

```javascript
const stopAndResetVideo = () => {
    if (videoRef.current) {
      setIsPlaying(false); 
      console.log("Videoref", videoRef.current)
      videoRef?.current?.seek(0); // Seek to the beginning after a short delay
    }
  }```

and I see:
```

` LOG  Videoref {"dismissFullscreenPlayer": [Function anonymous], "pause": [Function anonymous], "presentFullscreenPlayer": [Function anonymous], "restoreUserInterfaceForPictureInPictureStopCompleted": [Function anonymous], "resume": [Function anonymous], "save": [Function anonymous], "seek": [Function anonymous]}`
 `WARN  Possible Unhandled Promise Rejection (id: 4):
TypeError: _VideoNativeComponent.VideoManager.seek is not a function (it is undefined)`
```


### Reproduction

repository link

### Reproduction

I can provide a stand alone if you really need; this is highly reproducible for me; this was working fine in V5.  I would also be happy to see an example program with seek() working in it.   I'm getting the videoref from the ref prop in the Video element like the current example:

```javascript
<Video
  ref={(ref: VideoRef) => {
    videoRef.current = ref;
  }}
...
/>
```

**Comment by freeboub** [comment]
There is a sample in the repository, do you reproduce the issue with it ?

**Comment by eedeebee** [comment]
Thanks!  That sample is quite a lot of code to be honest.  Does seek work
in it for you?  I did my best to grab a snippet from it in my app but I can
put together a smaller sample for repo if you believe seek works in beta 6

Eric

**Comment by lou-shy** [comment]
I have similar problem after updating from V6.0.0-beta.6 to V6.0.0-beta.7. In my case it throws when using resume() and pause() methods.

**Comment by freeboub** [comment]
Can you please clarify which react native version you use please?

**Comment by lou-shy** [comment]
@freeboub I'm using React Native 0.73.6

**Comment by KrzysztofMoch** [comment]
Please check `6.0.0-beta.8` (I couldn't reproduce issue with this version)

**Comment by lou-shy** [comment]
@KrzysztofMoch I've checked 6.0.0-beta.8, it works fine now without throwing.

**Comment by KrzysztofMoch** [comment]
Nice, let's close then
