### ISSUE TITLE
[BUG]: tvOS failed build on 6.1.1

### ISSUE THREAD

**Issue by ryancw** [TheWidlarzGroup/react-native-video#3829]
### Version

6.1.1

### What platforms are you having the problem on?

Apple tvOS

### Architecture

Old architecture

### What happened?

Upgraded to 6.1.1, getting 6 compilation errors coming from `NowPlayingInfoCenterManager`.
<img width="655" alt="Screenshot 2024-05-23 at 10 02 53 AM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/1441140/a76a0610-b0da-4b62-ac4c-b5b474e6a386">

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: Upgrade to 6.1.1 from 5.2.1, pod install. Seeing the issue on 6.0.0 too.

**Comment by ryancw** [comment]
I think this is related to using Xcode 14.2. Currently updating to 14.3 (Swift 5.8) and will report back.

**Comment by ryancw** [comment]
Confirming upgrading to Swift 5.8 (Xcode 14.3) fixes the issue.
