### ISSUE TITLE
Build failures on Android after upgrading from 6.0.0-alpha.4 to 6.0.0-beta.0

### ISSUE THREAD

**Issue by mitchdowney** [TheWidlarzGroup/react-native-video#3392]
Ever since upgrading to 6.0.0-beta.0, I am unable to build our app on Android successfully. Here are the errors:

```
BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:25: error: package androidx.activity does not exist
import androidx.activity.OnBackPressedCallback;
                        ^
/Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/FullScreenPlayerView.java:9: error: package androidx.activity does not exist
import androidx.activity.OnBackPressedCallback;
                        ^
/Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/FullScreenPlayerView.java:17: error: cannot find symbol
    private final OnBackPressedCallback onBackPressedCallback;
                  ^
  symbol:   class OnBackPressedCallback
  location: class FullScreenPlayerView
/Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/FullScreenPlayerView.java:19: error: cannot find symbol
    public FullScreenPlayerView(Context context, ExoPlayerView exoPlayerView, LegacyPlayerControlView playerControlView, OnBackPressedCallback onBackPressedCallback) {
                                                                                                                         ^
  symbol:   class OnBackPressedCallback
  location: class FullScreenPlayerView
/Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:400: error: cannot find symbol
            fullScreenPlayerView = new FullScreenPlayerView(getContext(), exoPlayerView, playerControlView, new OnBackPressedCallback(true) {
                                                                                                                ^
  symbol:   class OnBackPressedCallback
  location: class ReactExoplayerView
/Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:401: error: method does not override or implement a method from a supertype
                @Override
                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mitcheldowney/repos/podverse-rn/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors
```

I have tried the Android specific steps in the [installation docs](https://react-native-video.github.io/react-native-video/installation), but my changes seem to have no effect. I get the same 6 errors every time.

It seemed like this PR https://github.com/react-native-video/react-native-video/pull/3376 might be related, so I tried checking out the master branch from that commit, but I still get the same issues.

Does anyone have insight into what we need to do differently to get this working? Our .gradle files can be found here: https://github.com/podverse/podverse-rn/tree/develop/android

**Comment by mitchdowney** [comment]
I have even tried using the values I can see in the example .gradle files https://github.com/react-native-video/react-native-video/tree/master/examples/basic/android, and matching them with the installation docs as best I can...and I get the same exact 6 errors still 😖

Any help explaining what the underlying issue is here, and how I can fix it, would be greatly appreciated.

**Comment by mitchdowney** [comment]
The app has built! The number of config changes makes me nervous, as I'm not a competent Android developer, but I'm not seeing an issue so far.

I made all of these changes *except* the `RNVUseExoplayerIMA = true` when I posted my last comment, but after I tried throwing that in there, in addition to the other changes, the app was able to build again.

But do I want this value set to true? We definitely do not have or want to add interactive ads in our app. Is RNV 6.0.0-beta.0 just not working unless you enable IMA support?

If you have any thoughts on my config changes in this PR I'd appreciate it:

https://github.com/podverse/podverse-rn/pull/2082/files

**Comment by KrzysztofMoch** [comment]
Just created new project with `npx react-native init` and install `react-native-video@6.0.0-beta.0` and I was able to run it without any problems. Even stranger is that `RNVUseExoplayerIMA = true` is working for you, because `beta.0` has issue with IMA (will be fixed in `beta.1`) that crash build

**Comment by freeboub** [comment]
I confirm you shouldn't use IMA if you don't need it (you will have issues when you will on store).
Regarding to the changes you made:

```
configurations.all {
        resolutionStrategy { force 'androidx.core:core:1.9.0' }
    }
```

I don't think this should be set in react native video, but It is better to include it in the app.

```
- implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
+ implementation 'androidx.appcompat:appcompat:1.2.0' 
```
I am not sure this dependancy is still necessary... 
I cannot find any appcompat in the code ...

Changes in: android/build.gradle
It hsould be possible to handle tham on application side.
If not the good patch would be to extend these definitions

new release should come soon, I will ping you once available.
Thank you

**Comment by mitchdowney** [comment]
Thanks for trying to help. There are 6 errors but if I only focus on one...

> error: package androidx.activity does not exist
> import androidx.activity.OnBackPressedCallback;

What can cause `androidx.activity` to not exist in that file? Do I need to add an `implementation` for `androidx.activity` in my `android/app/build.gradle`? I am guessing not or this would probably be in the installation instructions already.

**Comment by mitchdowney** [comment]
All 6 of the build errors go away when I add this into react-native-video's build.gradle file:

```
implementation 'androidx.activity:activity-ktx:1.7.0'
```

I guess that would be simple enough for me to `npx patch-package` in our app for now.

Any ideas why the example app apparently doesn't need that dependency imported, but our app does?

Here is the PR with my changes that got it working for me: https://github.com/podverse/podverse-rn/pull/2083/files

**Comment by KrzysztofMoch** [comment]
Not sure. New app or examples work without it. Maybe it is react native version ? 🤔

**Comment by mitchdowney** [comment]
Ok, we're on RN 0.66, so our setup is pretty old. It's a single line patch to get RNV working in our app, so I can live with that for now. Feel free to close the issue. Thanks for your help!

**Comment by freeboub** [comment]
@mitchdowney I built a beta.1 with the last fixes for IMA.
regarding to your issue, can you please clarify which androidx version you use ?
on sample we uses 1.9. I think that can be the issue.
Can the issue be fixed if you move this version ?
do you have: androidxCoreVersion defined in ext section of gradle file ? 

Note: I think you will not be able to push ios version on app store with RN 0.66 due to xcode issue. but maybe this is not needed in your project.
Let me know if we need to investigate more, or if we can close the issue.
Thank you.

**Comment by mitchdowney** [comment]
> can you please clarify which androidx version you use ?
> on sample we uses 1.9. I think that can be the issue.
> Can the issue be fixed if you move this version ?
> do you have: androidxCoreVersion defined in ext section of gradle file ?

In our build.grade we have androidXCore = "1.7.0", but I could have swore I tried changing that to "1.9.0" to match with the example app...maybe androidxCoreVerision is different / correct? Well I just tried adding that key/value pair, and I get the same 6 errors.

Our ./android/build.gradle ext looks like this:

```
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "30.0.2"
        kotlinVersion = '1.7.0'
        ndkVersion = '23.0.7599858'
        androidXCore = "1.9.0"
        androidxCoreVersion = "1.9.0"
        RNVUseExoplayerIMA = false
    }
```

And [this is what it looks like](https://github.com/podverse/podverse-rn/blob/0bc3d3d0b22cc0f3b92580a55fc2dafdf7d431b7/android/build.gradle) before those changes.

> Note: I think you will not be able to push ios version on app store with RN 0.66 due to xcode issue. but maybe this is not needed in your project.

Oh boy 😯 is that due to something new in RNV 6.0.0-beta.1, or just because of something with RN 0.66? Our app is currently in TestFlight with 6.0.0-beta.0, distributed to open testers, and made it through that review phase, but maybe this is something that their public release review process may turn up?

And again, if this is just something quirky about our app environment, and no one else is running into it, feel free to close the issue as we have a patch that seems to work.

**Comment by freeboub** [comment]
@mitchdowney I have just open a pull request with the change.
As we use this dependancy, it makes sense to declare it. (I don't undertand how sample build ...)

> Oh boy 😯 is that due to something new in RNV 6.0.0-beta.1, or just because of something with RN 0.66? Our app is currently in TestFlight with 6.0.0-beta.0, distributed to open testers, and made it through that review phase, but maybe this is something that their public release review process may turn up?

No from what I heard (I cannot find official doc), 0.66 need a version xcode which is deprecated. I think it is not possible to build RN 0.66 with the last xcode version (nothing related to this package).

Let me know if it is ok for you !

**Comment by mitchdowney** [comment]
@freeboub cool thanks for the PR!

As for XCode...our latest app version was just accepted for prod to AppStore. We may not be using the latest XCode in our AppCenter build pipeline though, and AppCenter appears to be down right now so I can't check which one we're using :/

One more question, when you say "latest" Xcode are you referring to the latest public release, or latest beta?

**Comment by freeboub** [comment]
@mitchdowney The latest public release

**Comment by mitchdowney** [comment]
Ok hmm...our last publish to AppStore using Xcode 14.2 and React Native 0.66.5 was accepted yesterday, so we're not seeing issues with that combination yet.

**Comment by freeboub** [comment]
The fixed has been included in beta.2
Let's close this issue. @mitchdowney let us know if this is ok now.
Thank you

**Comment by mitchdowney** [comment]
I just removed my patch file, then upgraded to 6.0.0-beta.2 locally, and it built successfully! It looks like the fix worked. Thanks for the quick attention on this.

**Comment by baim87** [comment]
1. Try to delete your package-lock.json, 
2. run `rm -rf node_modules/` on the root folder
3. Make sure the correct version is stated on the package.json.
4. npm install
5. Restart the metro
