### ISSUE TITLE
[BUG]: _videoRef$current.setNativeProps is not a function (it is undefined)

### ISSUE THREAD

**Issue by amitkumarcoding** [TheWidlarzGroup/react-native-video#3843]
### Version

6.1.2

### Architecture

Old architecture

### What happened?

A bug occurred!

To dynamically change the token, I use the following code:

```
videoRef.current?.setNativeProps({
      source: {
        uri: uri,
        type: 'm3u8',
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    });
```
The above code works well in version `5.2.1`.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

open the app
run the video player

**Comment by KrzysztofMoch** [comment]
setNativeProps is deprecated, you should save source in state - if you want to update source via ref you will need to create your own component with forwardRef that will handle update of source state

**Comment by amitmehtacode** [comment]
but it reset the video duration

**Comment by amitkumarcoding** [comment]
> setNativeProps is deprecated, you should save source in state - if you want to update source via ref you will need to create your own component with forwardRef that will handle update of source state

@KrzysztofMoch After making these changes, the progress value goes back by 15 seconds with each token change.

**Comment by amitkumarcoding** [comment]
@KrzysztofMoch 
In the previous version, I managed to change the token like this, and it worked fine without affecting the progress value:

```
videoRef.current?.setNativeProps({
      source: {
        uri: uri,
        type: 'm3u8',
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    });
```

**Comment by freeboub** [comment]
Hello @amitmehtacode, I am a bit surprised, because header is not parsed in source 🤔 
There is only a field "requestHeaders" in source which is not documented :/

**Comment by amitkumarcoding** [comment]
> Hello @amitmehtacode, I am a bit surprised, because header is not parsed in source 🤔 There is only a field "requestHeaders" in source which is not documented :/

But If I remove the `headers:{}` then the video is not playable.

**Comment by amitkumarcoding** [comment]
> Hello @amitmehtacode, I am a bit surprised, because header is not parsed in source 🤔 There is only a field "requestHeaders" in source which is not documented :/

I also put `requestHeaders` but still the video is not playable 🙁

**Comment by amitkumarcoding** [comment]
@freeboub Any update for the same.
