### PR TITLE
fix: swift compilation errors

### PR DESCRIPTION
**Pull request by matinzd**
Fix swift compilation errors. https://github.com/react-native-video/react-native-video/issues/2837

@freeboub

### CODE REVIEW

**Comment by freeboub** [comment]
@matinzd  can it also fix this : https://github.com/react-native-video/react-native-video/issues/2811 ?

**Comment by matinzd** [comment]
> @matinzd can it also fix this : #2811 ?

I will try but let’s first merge this and we can fix that later in another PR.

**Comment by freeboub** [comment]
> > @matinzd can it also fix this : #2811 ?
> 
> I will try but let’s first merge this and we can fix that later in another PR.

Yes sure, it was just an open question to keep backlog clean ;)

**Comment by freeboub** [comment]
@nickfujita your review is wellcome :)

**Comment by minhas-weoveri** [comment]
I verified this code works fine with "react-native-video": "6.0.0-alpha.1",

**Comment by matinzd** [comment]
> I verified this code works fine with "react-native-video": "6.0.0-alpha.1",

Please do not merge this. I am trying to upgrade exmaple projects to latest react native version. 
Then we need to test these changes with the latest version. 

AFAIK, the previous code should work fine, but there are some issues with the swift version maybe or with the new react native upgrades or compile problems.

**Comment by evoactivity** [comment]
I'm on the same version of react native as described in the issue. I have not needed to apply any patches to build for iOS. I think this is a problem with the user's environment.

**Comment by freeboub** [comment]
@matinzd can you update on this PR please ?

**Comment by matinzd** [comment]
> @matinzd can you update on this PR please ?

I drafted this PR and it seems that there is something wrong with the user environment as @evoactivity mentioned. This PR does not make sense anymore since all these APIs are available on Apple's documentation right now without any deprecation.

**Comment by freeboub** [comment]
OK, let's cancel this PR, thanks
