### PR TITLE
fix(ReactVideoProps): add accessibility & testID in typing

### LINKED ISSUE #3427: Typing - Missing accessibilityLabel in ReactVideoProps
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-video@6.0.0-beta.2` for the project I'm working on.

After the upgrade (from 5.2.1 to 6.0.0-beta.2), typing broke for accessibilityLabel of Video - even if it is actually taken into account in the test after!

### Without the fix:
`TS error= Property 'accessibilityLabel' does not exist on type 'IntrinsicAttributes & ReactVideoProps'
`
```typescript
import Video, { IgnoreSilentSwitchType, ReactVideoProps, ResizeMode } from 'react-native-video';

export const TF1Video = (props: ReactVideoProps) => {
  return (
    <Video
      muted={true}
      repeat={true}
      resizeMode={ResizeMode.COVER}
      rate={1.0}
      ignoreSilentSwitch={IgnoreSilentSwitchType.OBEY}
      accessibilityLabel="TF1video" // 🐞🐞  TS error= Property 'accessibilityLabel' does not exist on type 'IntrinsicAttributes & ReactVideoProps'
      {...props}
    />
  );
};

``` 

It was okay in previous version of lib (5.2.1). 
It's only a TS issue, in my test `screen.getByLabelText('TF1video')` works! 👌 

### With the fix 
After adding it: TypeScript happy 😊 
image
 

### Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-video/lib/types/video.d.ts b/node_modules/react-native-video/lib/types/video.d.ts
index f61eda2..96b43d1 100644
--- a/node_modules/react-native-video/lib/types/video.d.ts
+++ b/node_modules/react-native-video/lib/types/video.d.ts
@@ -129,6 +129,7 @@ export declare enum PosterResizeModeType {
     STRETCH = "stretch"
 }
 export interface ReactVideoProps extends ReactVideoEvents {
+    accessibilityLabel?: string;
     source?: ReactVideoSource;
     drm?: Drm;
     style?: StyleProp<ViewStyle>;

```

On the lib, it could / should probably be on the `types/video.ts` file? 
I may open a PR for it, if pertinent!

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by delphinebugner**
### Change Description 
Fixes https://github.com/react-native-video/react-native-video/issues/3427

As suggested, ReactVideoProps now extends AccessibilityProps. 
The testID has been added on its own, as in [ViewPropsTypes in React Native](https://github.com/facebook/react-native/blob/dae4a11e901696f7c205e19df6f0b306319be43a/packages/react-native/Libraries/Components/View/ViewPropTypes.d.ts#L250)!

### Test plan
I tested this on my project ; we have now : 
- No TS error when adding testID or accessibility props in a Video
```typescript
import Video, { ReactVideoProps } from 'react-native-video';

export const TF1Video = (props: ReactVideoProps) => {
  return (
    <Video
      accessibilityHint="A React Native Video" // ✅ ts okay
      accessibilityLabel="A good React Native Video label" // ✅ ts okay
      testID="rn-video" // ✅ ts okay
      {...props}
    />
  );
};

``` 
- Autocompletion 
image

- We still have `screen.getByLabelText('"A good React Native Video label')` working using RNTL
- We still have all props appearing in spnashots :
```
exports[`React Native Video renders correctly`] = `
  <RCTVideo
    accessibilityHint="A React Native Video"
    accessibilityLabel="A good label"
    {...}
    testID="rn-video"
  />
```

### Checks 
[ x ] No need for doc update
[  ] Changelog modified -> no but is it this still needed?

### CODE REVIEW

**Review by freeboub — APPROVED** [review]

**Review by KrzysztofMoch — APPROVED** [review]
LGTM 🙌
