### ISSUE TITLE
[Android] Crash on Android 16 when rendering <Video /> (RN 0.85.2)

### ISSUE THREAD

**Issue by Yeasirarafat53** [TheWidlarzGroup/react-native-video#4895]
### What happened?

The app crashes immediately when rendering the `<Video />` component on Android — even with a simple remote MP4 URL. There is no UI rendered, and the crash happens instantly as soon as the component is mounted.

Expected behavior: the video should load and play normally.

Actual behavior: the app crashes immediately when the `<Video />` component is rendered.

Additional context:
- Internet permission is already added in `AndroidManifest.xml`
- Clean build has been performed
- Issue occurs with both remote and local video sources
- Also observed similar crashes when using video files generated from VisionCamera

Minimal code to reproduce:

```jsx
import React from 'react'
import { View } from 'react-native'
import Video from 'react-native-video'

export default function App() {
  return (
    <View style={{ flex: 1 }}>
      <Video
        source={{ uri: 'https://www.w3schools.com/html/mov_bbb.mp4' }}
        style={{ width: '100%', height: 200 }}
        controls
      />
    </View>
  )
}
```

### Steps to reproduce

1. Add a `<Video />` component with a remote MP4 source (e.g. `https://www.w3schools.com/html/mov_bbb.mp4`) and the `controls` prop, as shown in the minimal code above.
2. Run the app on an Android 16 device (Samsung A54).
3. Observe that the app crashes immediately as soon as the component is mounted, with no UI rendered.

### react-native-video version

6.19.2

### react-native version

0.85.2

### Platforms

Android

### OS version

Android 16

### Device

Real device

### Media / source type

MP4 / progressive

**Comment by Ibad9** [comment]
Same issue. I get this android studio logs.

FATAL EXCEPTION: main
                                                                                                    Process: com.mcontent, PID: 19402
                                                                                                    java.lang.NoSuchMethodError: No direct method <init>(Landroidx/media3/exoplayer/upstream/DefaultAllocator;IIIIIZIZ)V in class Landroidx/media3/exoplayer/DefaultLoadControl; or its super classes (declaration of 'androidx.media3.exoplayer.DefaultLoadControl' appears in /data/app/~~XyODgJvJ6c3wCjc_iANonw==/com.mcontent-rIWSyKURgrTvcDEd8yz0Gg==/base.apk!classes21.dex)
                                                                                                    	at com.brentvatne.exoplayer.ReactExoplayerView$RNVLoadControl.<init>(ReactExoplayerView.java:568)
                                                                                                    	at com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerCore(ReactExoplayerView.java:724)
                                                                                                    	at com.brentvatne.exoplayer.ReactExoplayerView.lambda$initializePlayer$7(ReactExoplayerView.java:646)
                                                                                                    	at com.brentvatne.exoplayer.ReactExoplayerView.$r8$lambda$DP9m-GVHZ1UV7-CzFpYsYGtcF3c(Unknown Source:0)
                                                                                                    	at com.brentvatne.exoplayer.ReactExoplayerView$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by Ibad9** [comment]
@Yeasirarafat53 try this in android/build.gradle under 

allProjects {

..rest of the code.

    configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.media3') {
                details.useVersion '1.8.0'
                details.because 'Pin to react-native-video 6.19.x bytecode (DefaultLoadControl ABI)'
            }
        }
    }

}

**Comment by Yeasirarafat53** [comment]
> [@Yeasirarafat53](https://github.com/Yeasirarafat53) try this in android/build.gradle under
> 
> allProjects {
> 
> ..rest of the code.
> 
> ```
> configurations.all {
>     resolutionStrategy.eachDependency { details ->
>         if (details.requested.group == 'androidx.media3') {
>             details.useVersion '1.8.0'
>             details.because 'Pin to react-native-video 6.19.x bytecode (DefaultLoadControl ABI)'
>         }
>     }
> }
> ```
> 
> }

```
buildscript {
    ext {
        buildToolsVersion = "36.0.0"
        minSdkVersion = 24
        compileSdkVersion = 36
        targetSdkVersion = 36
        ndkVersion = "27.1.12297006"
        kotlinVersion = "2.1.20"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath 'com.google.gms:google-services:4.4.3'
    }


configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'androidx.media3') {
            details.useVersion '1.8.0'
            details.because 'Pin to react-native-video 6.19.x bytecode (DefaultLoadControl ABI)'
        }
    }
}


}

apply plugin: "com.facebook.react.rootproject"
```

like this?

**Comment by jsdevrazuislam** [comment]
Have you guys found any solution yet? I’m still facing the same issue as well.
I have two apps — one is working fine, but the other one isn’t working, and I still can’t figure out what the problem is.

**Comment by Prajwaltechversant** [comment]
+1
Fatal Exception: java.lang.NoSuchMethodError

**Comment by Yeasirarafat53** [comment]
> Have you guys found any solution yet? I’m still facing the same issue as well. I have two apps — one is working fine, but the other one isn’t working, and I still can’t figure out what the problem is.

Still haven't found a solution.

**Comment by enamulays** [comment]
I am facing the same java.lang.NoSuchMethodError crash on Android with react-native-video 6.19.2. I tried adding the resolutionStrategy to android/build.gradle as suggested above, but the crash still persists.

**Comment by RakibHossain621** [comment]
Still facing this issue! I’ve tried comparing two of my apps; one is working fine, but the other isn't. I haven't found a fix yet. Any updates or solutions from anyone?"

**Comment by josegiufrida** [comment]
For us, this happened when we updated dependencies and React Native from 0.77 to 0.84. The solution I found was to install the new version 7; I used the latest available version: 7.0.0-beta.9, and the error disappeared. 

Note: I found some errors in the documentation for v7, and I don't know if it's ready for production in its current state.

**Comment by jsdevrazuislam** [comment]
Hey everyone! I finally found a solution that’s working perfectly for me, and I wanted to share it with you all. If you’ve been running into the same issues, here is how I fixed it:

Step 1: Update your Android build configuration
Navigate to android/build.gradle and update your script with the following code. This ensures all your media dependencies and SDK versions are aligned:

```

buildscript {
    ext {
        buildToolsVersion = "36.0.0"
        minSdkVersion = 24
        compileSdkVersion = 36
        targetSdkVersion = 36
        ndkVersion = "28.2.13676358"
        kotlinVersion = "2.1.20"
        media3Version = "1.4.1"
        RNVideo_media3Version = media3Version
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath 'com.google.gms:google-services:4.4.4'
    }
}

apply plugin: "com.facebook.react.rootproject"

allprojects {
    configurations.all {
        resolutionStrategy {
            force "androidx.media3:media3-exoplayer:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-exoplayer-dash:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-exoplayer-hls:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-exoplayer-smoothstreaming:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-exoplayer-rtsp:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-datasource:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-datasource-okhttp:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-ui:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-session:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-common:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-extractor:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-database:${rootProject.ext.media3Version}"
            force "androidx.media3:media3-decoder:${rootProject.ext.media3Version}"
        }
    }
`}`
```
Step 2: Clean and Rebuild
Once the code is in place, clear your previous build cache by running:

`./gradlew clean`

After that, you can rebuild your app. I really hope this helps clear up the issues for you as it did for me! Let me know if it works.

**Comment by Mootzali** [comment]
+1

**Comment by Steven-zion** [comment]
same problem, any solutions?

**Comment by Steven-zion** [comment]
> Hey everyone! I finally found a solution that’s working perfectly for me, and I wanted to share it with you all. If you’ve been running into the same issues, here is how I fixed it:
> 
> Step 1: Update your Android build configuration Navigate to android/build.gradle and update your script with the following code. This ensures all your media dependencies and SDK versions are aligned:
> 
> ```
> 
> buildscript {
>     ext {
>         buildToolsVersion = "36.0.0"
>         minSdkVersion = 24
>         compileSdkVersion = 36
>         targetSdkVersion = 36
>         ndkVersion = "28.2.13676358"
>         kotlinVersion = "2.1.20"
>         media3Version = "1.4.1"
>         RNVideo_media3Version = media3Version
>     }
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle")
>         classpath("com.facebook.react:react-native-gradle-plugin")
>         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
>         classpath 'com.google.gms:google-services:4.4.4'
>     }
> }
> 
> apply plugin: "com.facebook.react.rootproject"
> 
> allprojects {
>     configurations.all {
>         resolutionStrategy {
>             force "androidx.media3:media3-exoplayer:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-exoplayer-dash:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-exoplayer-hls:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-exoplayer-smoothstreaming:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-exoplayer-rtsp:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-datasource:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-datasource-okhttp:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-ui:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-session:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-common:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-extractor:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-database:${rootProject.ext.media3Version}"
>             force "androidx.media3:media3-decoder:${rootProject.ext.media3Version}"
>         }
>     }
> `}`
> ```
> 
> Step 2: Clean and Rebuild Once the code is in place, clear your previous build cache by running:
> 
> `./gradlew clean`
> 
> After that, you can rebuild your app. I really hope this helps clear up the issues for you as it did for me! Let me know if it works.

which version of `react-native-video` and `react-native-vision-camera` are you running, and does your app use HLS adaptive streaming with track selection? I'm hitting a different crash at media3 1.4.1 (onTracksSelected not implemented) so trying to figure out if our setups actually match before I test this

**Comment by jsdevrazuislam** [comment]
> > Hey everyone! I finally found a solution that’s working perfectly for me, and I wanted to share it with you all. If you’ve been running into the same issues, here is how I fixed it:
> > Step 1: Update your Android build configuration Navigate to android/build.gradle and update your script with the following code. This ensures all your media dependencies and SDK versions are aligned:
> > ```
> > 
> > buildscript {
> >     ext {
> >         buildToolsVersion = "36.0.0"
> >         minSdkVersion = 24
> >         compileSdkVersion = 36
> >         targetSdkVersion = 36
> >         ndkVersion = "28.2.13676358"
> >         kotlinVersion = "2.1.20"
> >         media3Version = "1.4.1"
> >         RNVideo_media3Version = media3Version
> >     }
> >     repositories {
> >         google()
> >         mavenCentral()
> >     }
> >     dependencies {
> >         classpath("com.android.tools.build:gradle")
> >         classpath("com.facebook.react:react-native-gradle-plugin")
> >         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
> >         classpath 'com.google.gms:google-services:4.4.4'
> >     }
> > }
> > 
> > apply plugin: "com.facebook.react.rootproject"
> > 
> > allprojects {
> >     configurations.all {
> >         resolutionStrategy {
> >             force "androidx.media3:media3-exoplayer:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-exoplayer-dash:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-exoplayer-hls:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-exoplayer-smoothstreaming:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-exoplayer-rtsp:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-datasource:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-datasource-okhttp:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-ui:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-session:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-common:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-extractor:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-database:${rootProject.ext.media3Version}"
> >             force "androidx.media3:media3-decoder:${rootProject.ext.media3Version}"
> >         }
> >     }
> > `}`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Step 2: Clean and Rebuild Once the code is in place, clear your previous build cache by running:
> > `./gradlew clean`
> > After that, you can rebuild your app. I really hope this helps clear up the issues for you as it did for me! Let me know if it works.
> 
> which version of `react-native-video` and `react-native-vision-camera` are you running, and does your app use HLS adaptive streaming with track selection? I'm hitting a different crash at media3 1.4.1 (onTracksSelected not implemented) so trying to figure out if our setups actually match before I test this

We're currently using:

```json
{
  "react-native-video": "6.19.1",
  "react-native-vision-camera": "^5.0.6"
}
```

Yes, our app supports HLS adaptive streaming. We are streaming HLS content and the player handles adaptive bitrate playback correctly.

At the moment, we're not seeing the specific `onTracksSelected` / Media3 1.4.1 crash you're describing, but our setup does include HLS playback. If your investigation points to track selection being involved, please let me know what you've found and I can compare it against our implementation to see if there are any meaningful differences.

**Comment by TWG-AI** [comment]
Thanks for the report. Looking at the comments here, the crash stack (`NoSuchMethodError: No direct method <init>(...DefaultAllocator...)V in class DefaultLoadControl`) is the same Media3 API compatibility issue also reported in #4900. They share the same root cause: rnv v6's internal `DefaultLoadControl` subclass uses a constructor signature that was changed in newer Media3 versions pulled in by newer RN releases or co-installed packages.

The workaround suggested in the comments (pinning `androidx.media3` to `1.8.0`) may help, but can conflict if other packages need a newer version. This has been logged for the team alongside #4900.

> I'm an AI assistant — please verify the details above.
