### ISSUE TITLE
[Bug]: Audio isn't getting recorded when using react native vision camera

### ISSUE THREAD

**Issue by TikshaK** [TheWidlarzGroup/react-native-video#4843]
### What happened?

Android build fails to compile when using react-native-video `6.7.0` with React Native `0.81.1`. The user originally used `6.17.0` (Android worked fine), then downgraded to `6.7.0` (to get audio recording working in their flow alongside react-native-vision-camera), and now the Android build no longer completes.

The Kotlin compilation fails because the older react-native-video sources are incompatible with the `ReadableMap`/`Event` APIs in RN 0.81.1 (nullable `ReadableMap?` receivers and `Event` generic bounds / `Int` argument mismatches).

Key errors:

```
e: .../react-native-video/android/src/main/java/com/brentvatne/common/api/CMCDProps.kt:40:31 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'ReadableMap?'.
e: .../CMCDProps.kt:41:39 ...
e: .../CMCDProps.kt:42:48 ...
e: .../CMCDProps.kt:43:48 ...
e: .../react-native-video/android/src/main/java/com/brentvatne/common/api/SideLoadedTextTrackList.kt:27:46 Initializer type mismatch: expected 'ReadableMap', actual 'ReadableMap?'.
e: .../SideLoadedTextTrackList.kt:27:46 Type mismatch: inferred type is 'ReadableMap?', but 'ReadableMap' was expected.
e: .../react-native-video/android/src/main/java/com/brentvatne/common/api/Source.kt:237:50 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'ReadableMap?'.
e: .../Source.kt:237:73 ...
e: .../Source.kt:238:52 ...
e: .../Source.kt:238:77 ...
e: .../react-native-video/android/src/main/java/com/brentvatne/common/react/VideoEventEmitter.kt:286:53 Type argument is not within its bounds: must be subtype of 'Event<Event<*>>'.
e: .../VideoEventEmitter.kt:286:63 Argument type mismatch: actual type is 'Int', but 'Int' was expected.
e: .../VideoEventEmitter.kt:286:74 Argument type mismatch: actual type is 'Int', but 'Int' was expected.

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-video:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
BUILD FAILED in 55s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

Context: the user is using react-native-vision-camera to record video (needs a 30-second stop constraint) and downgraded react-native-video to `6.7.0` for audio recording, but the older version no longer builds on Android under RN 0.81.1.

### Steps to reproduce

1. Use a React Native `0.81.1` project on Android.
2. Install react-native-video `6.7.0`.
3. Build/install the Android app (e.g. `./gradlew app:installDebug` / `yarn android`).
4. Observe the `:react-native-video:compileDebugKotlin` task fails with the Kotlin `ReadableMap?` nullability and `Event`/`Int` type-mismatch errors shown above.

### react-native-video version

6.7.0

### react-native version

0.81.1

### Platforms

Android

### Last working version

6.17.0

**Comment by TWG-AI** [comment]
Thanks for the report. This has been logged. The core issue is likely an audio focus or audio session configuration conflict between rnv and vision camera on Android. As a note: using v6.7.0 with RN 0.81 is expected to have compilation issues since the older rnv code predates some RN API changes — we'd recommend staying on the latest v6 and tracking the audio session conflict as a separate fix.

> I'm an AI assistant — please verify the above.
