### ISSUE TITLE
[iOS] Crash react native 0.84

### ISSUE THREAD

**Issue by maksymhcode-care** [TheWidlarzGroup/react-native-video#4845]
After upgrading to 0.84 app started crashing as soon as i enter the screen with a video player

react_native_video/RCTVideoManager.swift:7: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

**Comment by nazacity80** [comment]
Same here

v7 beta6 is worknig fine

**Comment by lukechen-ct** [comment]
It works for me.

[react-native-video+6.19.0.patch](https://github.com/user-attachments/files/25516612/react-native-video%2B6.19.0.patch)

**Comment by ghost** [comment]
@lukechen-ct Thank you. It works for me too. You saved my life :)

**Comment by ugurdalkiran** [comment]
@lukechen-ct Thank you. :)

**Comment by toemmanuel** [comment]
I could not get this to work, my app still crash, please any solution to this?

**Comment by pranabkumarbehera** [comment]
@lukechen-ct Thanks ****

**Comment by moskalakamil** [comment]
Hey! Thanks for reporting this - fix is on the way

**Comment by moskalakamil** [comment]
Fixed in v6.19.1 🎉

**Comment by Yeasirarafat53** [comment]
I’m facing the same issue on React **Native 0.85.2** with **Android 16**.
The app crashes immediately when rendering the 
`<Video />` component (even with a simple remote MP4 URL).

**Comment by pranabkumarbehera** [comment]
@Yeasirarafat53 Just need to fix them :
Path :node_modules/react-native-video/ios/video/RCTVideoManager.swift --> Need to add this code (e.g. Line 7 to 9).
Just see the below image .

<img width="695" height="575" alt="Image" src="https://github.com/user-attachments/assets/d06f1c7c-e933-4b01-abec-880e66ca6953" />
