### ISSUE TITLE
Does it work with latest version of React Native?

### ISSUE THREAD

**Issue by SergiOnGit** [TheWidlarzGroup/react-native-video#997]
I install it with your provided steps but build fails

`D:\projects\testapp\android\app\src\main\java\com\testapp\MainApplication.java:6: error: package com.brentvatne.react does not exist
import com.brentvatne.react.ReactVideoPackage;
                           ^
D:\projects\testapp\android\app\src\main\java\com\testapp\MainApplication.java:28: error: cannot find symbol
            new ReactVideoPackage(),
                ^
  symbol: class ReactVideoPackage
2 errors
Incremental compilation of 1 classes completed in 1.153 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 37.835 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html`

**Comment by cobarx** [comment]
I have it working on Android with RN 0.55.3. 

Make sure you ran `rnpm link react-native-video`. You also may need to edit MainApplication.java and add RNVideoPackage to `getPackages()`

**Comment by arasemami** [comment]
Hi guys, I have the same issue,
package.json  -->

```  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-video": "^3.2.1",
    "react-native-video-controls": "^2.2.3"
  },
```

MainApplication.java ----->

```
import com.brentvatne.react.ReactVideoPackage;
```

```   @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactVideoPackage()
      );
    }```


settings.gradle ---->

`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
`

**Comment by AKACC** [comment]
Did you add   `implementation project(':react-native-video')` in your app/build.gradle ?@arasemami @SergiOnGit 
I guess they forget mention in their docs.
